package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateModelsFile generates the models.go file
func GenerateModelsFile(models []ModelInfo, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	var sb strings.Builder
	
	// Package declaration
	sb.WriteString("// Code generated by prisma-go. DO NOT EDIT.\n\n")
	sb.WriteString("package generated\n\n")
	
	// Imports
	hasDateTime := false
	for _, model := range models {
		for _, field := range model.Fields {
			if strings.Contains(field.GoType, "time.Time") {
				hasDateTime = true
				break
			}
		}
		if hasDateTime {
			break
		}
	}

	if hasDateTime {
		sb.WriteString("import (\n")
		sb.WriteString("\t\"time\"\n")
		sb.WriteString(")\n\n")
	}

	// Generate model structs
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("// %s represents the %s model\n", model.Name, model.Name))
		sb.WriteString(fmt.Sprintf("type %s struct {\n", model.Name))
		
		for _, field := range model.Fields {
			sb.WriteString(fmt.Sprintf("\t%s %s %s\n", field.GoName, field.GoType, field.Tags))
		}
		
		sb.WriteString("}\n\n")
		
		// Add TableName method
		sb.WriteString(fmt.Sprintf("// TableName returns the table name for %s\n", model.Name))
		sb.WriteString(fmt.Sprintf("func (%s) TableName() string {\n", model.Name))
		sb.WriteString(fmt.Sprintf("\treturn \"%s\"\n", model.TableName))
		sb.WriteString("}\n\n")
	}

	// Write to file
	filePath := filepath.Join(outputDir, "models.go")
	if err := os.WriteFile(filePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write models file: %w", err)
	}

	return nil
}

// GenerateClientFile generates the client.go file
func GenerateClientFile(models []ModelInfo, provider string, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	var sb strings.Builder
	
	// Package declaration
	sb.WriteString("// Code generated by prisma-go. DO NOT EDIT.\n\n")
	sb.WriteString("package generated\n\n")
	
	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"database/sql\"\n\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/runtime/client\"\n")
	sb.WriteString(")\n\n")

	// Main client struct
	sb.WriteString("// PrismaClient is the main client for database operations\n")
	sb.WriteString("type PrismaClient struct {\n")
	sb.WriteString("\t*client.PrismaClient\n")
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("\t%s *%sClient\n", model.Name, model.Name))
	}
	sb.WriteString("}\n\n")

	// New client function
	sb.WriteString("// NewPrismaClient creates a new Prisma client\n")
	sb.WriteString("func NewPrismaClient(connectionString string) (*PrismaClient, error) {\n")
	sb.WriteString(fmt.Sprintf("\tbaseClient, err := client.NewPrismaClient(\"%s\", connectionString)\n", provider))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\treturn nil, err\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tc := &PrismaClient{\n")
	sb.WriteString("\t\tPrismaClient: baseClient,\n")
	sb.WriteString("\t}\n\n")
	
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("\tc.%s = &%sClient{client: baseClient}\n", model.Name, model.Name))
	}
	
	sb.WriteString("\n\treturn c, nil\n")
	sb.WriteString("}\n\n")

	// Generate client for each model
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("// %sClient provides methods for %s operations\n", model.Name, model.Name))
		sb.WriteString(fmt.Sprintf("type %sClient struct {\n", model.Name))
		sb.WriteString("\tclient *client.PrismaClient\n")
		sb.WriteString("}\n\n")

		// FindMany
		sb.WriteString(fmt.Sprintf("// FindMany retrieves multiple %s records\n", model.Name))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindMany(ctx context.Context) ([]%s, error) {\n", model.Name, model.Name))
		sb.WriteString("\t// TODO: Implement query execution\n")
		sb.WriteString(fmt.Sprintf("\treturn []%s{}, nil\n", model.Name))
		sb.WriteString("}\n\n")

		// FindFirst
		sb.WriteString(fmt.Sprintf("// FindFirst retrieves the first %s record\n", model.Name))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindFirst(ctx context.Context) (*%s, error) {\n", model.Name, model.Name))
		sb.WriteString("\t// TODO: Implement query execution\n")
		sb.WriteString(fmt.Sprintf("\treturn &%s{}, nil\n", model.Name))
		sb.WriteString("}\n\n")

		// Create
		sb.WriteString(fmt.Sprintf("// Create creates a new %s record\n", model.Name))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Create(ctx context.Context, data %s) (*%s, error) {\n", model.Name, model.Name, model.Name))
		sb.WriteString("\t// TODO: Implement insert execution\n")
		sb.WriteString("\treturn &data, nil\n")
		sb.WriteString("}\n\n")
	}

	// Write to file
	filePath := filepath.Join(outputDir, "client.go")
	if err := os.WriteFile(filePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write client file: %w", err)
	}

	return nil
}

