package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// getColumnType returns the column type for a Go type
func getColumnType(goType string) string {
	baseType := strings.TrimPrefix(goType, "*")
	baseType = strings.TrimPrefix(baseType, "[]")

	switch baseType {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
		return "columns.IntColumn"
	case "string":
		if strings.HasPrefix(goType, "*") {
			return "columns.NullableStringColumn"
		}
		return "columns.StringColumn"
	case "bool":
		return "columns.BoolColumn"
	case "time.Time":
		return "columns.DateTimeColumn"
	case "float32", "float64":
		return "columns.IntColumn" // Use IntColumn for now, could add FloatColumn later
	default:
		return "columns.StringColumn" // Default fallback
	}
}

// getColumnConstructor returns the constructor function name for a column type
func getColumnConstructor(columnType string) string {
	switch columnType {
	case "columns.IntColumn":
		return "columns.NewIntColumn"
	case "columns.StringColumn":
		return "columns.NewStringColumn"
	case "columns.NullableStringColumn":
		return "columns.NewNullableStringColumn"
	case "columns.BoolColumn":
		return "columns.NewBoolColumn"
	case "columns.DateTimeColumn":
		return "columns.NewDateTimeColumn"
	default:
		return "columns.NewStringColumn"
	}
}

// GenerateModelsFile generates the models.go file
func GenerateModelsFile(models []ModelInfo, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	var sb strings.Builder

	// Package declaration
	sb.WriteString("// Code generated by prisma-go. DO NOT EDIT.\n\n")
	sb.WriteString("package generated\n\n")

	// Check for time.Time usage
	hasDateTime := false
	for _, model := range models {
		for _, field := range model.Fields {
			if strings.Contains(field.GoType, "time.Time") {
				hasDateTime = true
				break
			}
		}
		if hasDateTime {
			break
		}
	}

	// Write imports
	if hasDateTime {
		sb.WriteString("import (\n")
		sb.WriteString("\t\"time\"\n")
		sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/columns\"\n")
		sb.WriteString(")\n\n")
	} else {
		sb.WriteString("import (\n")
		sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/columns\"\n")
		sb.WriteString(")\n\n")
	}

	// Generate model structs
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("// %s represents the %s model\n", model.Name, model.Name))
		sb.WriteString(fmt.Sprintf("type %s struct {\n", model.Name))

		for _, field := range model.Fields {
			sb.WriteString(fmt.Sprintf("\t%s %s %s\n", field.GoName, field.GoType, field.Tags))
		}

		sb.WriteString("}\n\n")

		// Add TableName method
		sb.WriteString(fmt.Sprintf("// TableName returns the table name for %s\n", model.Name))
		sb.WriteString(fmt.Sprintf("func (%s) TableName() string {\n", model.Name))
		sb.WriteString(fmt.Sprintf("\treturn \"%s\"\n", model.TableName))
		sb.WriteString("}\n\n")
	}

	for _, model := range models {
		modelName := model.Name
		tableName := model.TableName

		// Generate column struct
		sb.WriteString(fmt.Sprintf("// %sColumns provides type-safe column references for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sColumns struct {\n", modelName))
		for _, field := range model.Fields {
			if !field.IsRelation {
				fieldName := field.GoName
				columnType := getColumnType(field.GoType)
				sb.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, columnType))
			}
		}
		sb.WriteString("}\n\n")

		// Generate column instance
		sb.WriteString(fmt.Sprintf("// %sColumnsInstance provides type-safe column references for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("var %sColumnsInstance = %sColumns{\n", modelName, modelName))
		for _, field := range model.Fields {
			if !field.IsRelation {
				fieldName := field.GoName
				columnName := toSnakeCase(field.Name)
				columnType := getColumnType(field.GoType)
				constructor := getColumnConstructor(columnType)
				sb.WriteString(fmt.Sprintf("\t%s: %s(\"%s\", \"%s\"),\n", fieldName, constructor, tableName, columnName))
			}
		}
		sb.WriteString("}\n\n")
	}

	// Write to file
	filePath := filepath.Join(outputDir, "models.go")
	if err := os.WriteFile(filePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write models file: %w", err)
	}

	return nil
}

// GenerateClientFile generates the client.go file
func GenerateClientFile(models []ModelInfo, provider string, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	var sb strings.Builder

	// Package declaration
	sb.WriteString("// Code generated by prisma-go. DO NOT EDIT.\n\n")
	sb.WriteString("package generated\n\n")

	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"database/sql\"\n")
	sb.WriteString("\t\"time\"\n\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/builder\"\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/columns\"\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/executor\"\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/query/sqlgen\"\n")
	sb.WriteString("\t\"github.com/satishbabariya/prisma-go/runtime/client\"\n")
	sb.WriteString(")\n\n")

	// Main client struct
	sb.WriteString("// PrismaClient is the main client for database operations\n")
	sb.WriteString("type PrismaClient struct {\n")
	sb.WriteString("\t*client.PrismaClient\n")
	for _, model := range models {
		sb.WriteString(fmt.Sprintf("\t%s *%sClient\n", model.Name, model.Name))
	}
	sb.WriteString("}\n\n")

	// New client function
	sb.WriteString("// NewPrismaClient creates a new Prisma client\n")
	sb.WriteString("func NewPrismaClient(connectionString string) (*PrismaClient, error) {\n")
	sb.WriteString(fmt.Sprintf("\tbaseClient, err := client.NewPrismaClient(\"%s\", connectionString)\n", provider))
	sb.WriteString("\tif err != nil {\n")
	sb.WriteString("\t\treturn nil, err\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tc := &PrismaClient{\n")
	sb.WriteString("\t\tPrismaClient: baseClient,\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// Create executor\n")
	sb.WriteString(fmt.Sprintf("\texec := executor.NewExecutor(baseClient.DB(), \"%s\")\n\n", provider))

	for _, model := range models {
		sb.WriteString(fmt.Sprintf("\tc.%s = &%sClient{\n", model.Name, model.Name))
		sb.WriteString("\t\tclient: baseClient,\n")
		sb.WriteString("\t\texecutor: exec,\n")
		sb.WriteString(fmt.Sprintf("\t\ttable: \"%s\",\n", model.TableName))
		sb.WriteString("\t\trelations: map[string]executor.RelationMetadata{\n")
		for _, rel := range model.Relations {
			if rel.ForeignKey != "" {
				sb.WriteString(fmt.Sprintf("\t\t\t\"%s\": executor.RelationMetadata{\n", rel.FieldName))
				sb.WriteString(fmt.Sprintf("\t\t\t\tRelatedTable: \"%s\",\n", rel.ForeignKeyTable))
				sb.WriteString(fmt.Sprintf("\t\t\t\tForeignKey: \"%s\",\n", toSnakeCase(rel.ForeignKey)))
				sb.WriteString(fmt.Sprintf("\t\t\t\tLocalKey: \"%s\",\n", toSnakeCase(rel.LocalKey)))
				sb.WriteString(fmt.Sprintf("\t\t\t\tIsList: %v,\n", rel.IsList))
				sb.WriteString("\t\t\t},\n")
			}
		}
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t}\n")
	}

	sb.WriteString("\n\treturn c, nil\n")
	sb.WriteString("}\n\n")

	// Add raw SQL methods to PrismaClient
	sb.WriteString("// Raw executes a raw SQL query and returns the result\n")
	sb.WriteString("func (c *PrismaClient) Raw(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {\n")
	sb.WriteString("\treturn c.PrismaClient.Raw(ctx, query, args...)\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// RawScan executes a raw SQL query and scans the results into the destination\n")
	sb.WriteString("func (c *PrismaClient) RawScan(ctx context.Context, dest interface{}, query string, args ...interface{}) error {\n")
	sb.WriteString("\treturn c.PrismaClient.RawScan(ctx, dest, query, args...)\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// RawExec executes a raw SQL statement (INSERT, UPDATE, DELETE) and returns the result\n")
	sb.WriteString("func (c *PrismaClient) RawExec(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {\n")
	sb.WriteString("\treturn c.PrismaClient.RawExec(ctx, query, args...)\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// RawQuery executes a raw SQL query and returns rows\n")
	sb.WriteString("func (c *PrismaClient) RawQuery(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error) {\n")
	sb.WriteString("\treturn c.PrismaClient.RawQuery(ctx, query, args...)\n")
	sb.WriteString("}\n\n")

	// Generate client for each model
	for _, model := range models {
		modelName := model.Name

		sb.WriteString(fmt.Sprintf("// %sClient provides methods for %s operations\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sClient struct {\n", modelName))
		sb.WriteString("\tclient *client.PrismaClient\n")
		sb.WriteString("\texecutor *executor.Executor\n")
		sb.WriteString("\ttable string\n")
		sb.WriteString("\trelations map[string]executor.RelationMetadata\n")
		sb.WriteString("}\n\n")

		// WhereBuilder type
		sb.WriteString(fmt.Sprintf("// %sWhereBuilder builds WHERE clauses for %s queries\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sWhereBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.WhereBuilder\n")
		sb.WriteString("\tclient *" + modelName + "Client\n")
		sb.WriteString("}\n\n")

		// QueryBuilder type
		sb.WriteString(fmt.Sprintf("// %sQueryBuilder builds complete queries for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sQueryBuilder struct {\n", modelName))
		sb.WriteString("\twhere *builder.WhereBuilder\n")
		sb.WriteString("\tjoins *builder.JoinBuilder\n")
		sb.WriteString("\torderBy *builder.OrderByBuilder\n")
		sb.WriteString("\tinclude *builder.IncludeBuilder\n")
		sb.WriteString("\tselect_ *builder.SelectBuilder\n")
		sb.WriteString("\tlimit *int\n")
		sb.WriteString("\toffset *int\n")
		sb.WriteString("\tclient *" + modelName + "Client\n")
		sb.WriteString("}\n\n")

		// Where method
		sb.WriteString("// Where starts building a WHERE clause\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Where() *%sWhereBuilder {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn &%sWhereBuilder{\n", modelName))
		sb.WriteString("\t\tWhereBuilder: builder.NewWhereBuilder(),\n")
		sb.WriteString("\t\tclient: c,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// FindMany with WHERE support
		sb.WriteString(fmt.Sprintf("// FindMany retrieves multiple %s records\n", modelName))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindMany(ctx context.Context) ([]%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn c.FindManyWhere(ctx, nil)\n"))
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("// FindManyWhere retrieves multiple %s records with WHERE clause\n", modelName))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindManyWhere(ctx context.Context, where *builder.WhereBuilder) ([]%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tvar results []%s\n", modelName))
		sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
		sb.WriteString("\tif where != nil {\n")
		sb.WriteString("\t\twhereClause = where.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\tif err := c.executor.FindManyWithRelations(ctx, c.table, nil, whereClause, nil, nil, nil, nil, c.relations, &results); err != nil {\n"))
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn results, nil\n")
		sb.WriteString("}\n\n")

		// Query method - starts a query builder
		sb.WriteString("// Query starts building a query with WHERE, ORDER BY, LIMIT, OFFSET\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Query() *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn &%sQueryBuilder{\n", modelName))
		sb.WriteString("\t\tclient: c,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// FindFirst with WHERE support
		sb.WriteString(fmt.Sprintf("// FindFirst retrieves the first %s record\n", modelName))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindFirst(ctx context.Context) (*%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn c.FindFirstWhere(ctx, nil)\n"))
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("// FindFirstWhere retrieves the first %s record with WHERE clause\n", modelName))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) FindFirstWhere(ctx context.Context, where *builder.WhereBuilder) (*%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tvar result %s\n", modelName))
		sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
		sb.WriteString("\tif where != nil {\n")
		sb.WriteString("\t\twhereClause = where.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\tif err := c.executor.FindFirstWithRelations(ctx, c.table, nil, whereClause, nil, nil, c.relations, &result); err != nil {\n"))
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn &result, nil\n")
		sb.WriteString("}\n\n")

		// Execute method for WhereBuilder
		sb.WriteString("// Execute executes the query with the WHERE clause\n")
		sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) Execute(ctx context.Context) ([]%s, error) {\n", modelName, modelName))
		sb.WriteString("\treturn w.client.FindManyWhere(ctx, w.WhereBuilder)\n")
		sb.WriteString("}\n\n")

		// ExecuteFirst method for WhereBuilder
		sb.WriteString("// ExecuteFirst executes the query and returns the first result\n")
		sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) ExecuteFirst(ctx context.Context) (*%s, error) {\n", modelName, modelName))
		sb.WriteString("\treturn w.client.FindFirstWhere(ctx, w.WhereBuilder)\n")
		sb.WriteString("}\n\n")

		// QueryBuilder methods - Where returns QueryBuilder for chaining
		sb.WriteString("// Where starts building a WHERE clause\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Where() *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.where == nil {\n")
		sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn q\n")
		sb.WriteString("}\n\n")

		// Where with column condition - type-safe version
		sb.WriteString("// WhereCondition adds a column-based condition (type-safe)\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) WhereCondition(cond columns.Condition) *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.where == nil {\n")
		sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tq.where.AddCondition(cond)\n")
		sb.WriteString("\treturn q\n")
		sb.WriteString("}\n\n")

		// WhereConditions with multiple conditions
		sb.WriteString("// WhereConditions adds multiple column-based conditions (type-safe)\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) WhereConditions(conds []columns.Condition) *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.where == nil {\n")
		sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tq.where.AddConditions(conds)\n")
		sb.WriteString("\treturn q\n")
		sb.WriteString("}\n\n")

		// Subquery helper method
		sb.WriteString("// Subquery creates a subquery builder for this model\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Subquery() *builder.SubqueryBuilder {\n", modelName))
		sb.WriteString(fmt.Sprintf("\treturn builder.NewSubqueryBuilder(c.table, c.executor.GetGenerator())\n"))
		sb.WriteString("}\n\n")

		// Add field-specific methods directly to QueryBuilder for chaining
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)
			goType := field.GoType

			// Equals
			sb.WriteString(fmt.Sprintf("// %sEquals filters where %s equals the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sEquals(value %s) *%sQueryBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString("\tif q.where == nil {\n")
			sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tq.where.Equals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn q\n")
			sb.WriteString("}\n\n")

			// NotEquals
			sb.WriteString(fmt.Sprintf("// %sNotEquals filters where %s does not equal the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sNotEquals(value %s) *%sQueryBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString("\tif q.where == nil {\n")
			sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tq.where.NotEquals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn q\n")
			sb.WriteString("}\n\n")

			// For numeric types
			if isNumericType(goType) {
				sb.WriteString(fmt.Sprintf("// %sGreaterThan filters where %s is greater than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sGreaterThan(value %s) *%sQueryBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString("\tif q.where == nil {\n")
				sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\tq.where.GreaterThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn q\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sLessThan filters where %s is less than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sLessThan(value %s) *%sQueryBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString("\tif q.where == nil {\n")
				sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\tq.where.LessThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn q\n")
				sb.WriteString("}\n\n")
			}

			// For string types
			if goType == "string" || strings.HasPrefix(goType, "*string") {
				sb.WriteString(fmt.Sprintf("// %sContains filters where %s contains the substring\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sContains(value string) *%sQueryBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString("\tif q.where == nil {\n")
				sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\tq.where.Like(\"%s\", \"%%\"+value+\"%%\")\n", dbColumnName))
				sb.WriteString("\treturn q\n")
				sb.WriteString("}\n\n")
			}

			// For optional fields
			if strings.HasPrefix(goType, "*") {
				sb.WriteString(fmt.Sprintf("// %sIsNull filters where %s is NULL\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sIsNull() *%sQueryBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString("\tif q.where == nil {\n")
				sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\tq.where.IsNull(\"%s\")\n", dbColumnName))
				sb.WriteString("\treturn q\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sIsNotNull filters where %s is not NULL\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) %sIsNotNull() *%sQueryBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString("\tif q.where == nil {\n")
				sb.WriteString("\t\tq.where = builder.NewWhereBuilder()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\tq.where.IsNotNull(\"%s\")\n", dbColumnName))
				sb.WriteString("\treturn q\n")
				sb.WriteString("}\n\n")
			}
		}

		// OrderBy methods for QueryBuilder
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)

			// OrderByAsc
			sb.WriteString(fmt.Sprintf("// OrderBy%sAsc orders results by %s ascending\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) OrderBy%sAsc() *%sQueryBuilder {\n", modelName, goFieldName, modelName))
			sb.WriteString("\tif q.orderBy == nil {\n")
			sb.WriteString("\t\tq.orderBy = builder.NewOrderByBuilder()\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tq.orderBy.Asc(\"%s\")\n", dbColumnName))
			sb.WriteString("\treturn q\n")
			sb.WriteString("}\n\n")

			// OrderByDesc
			sb.WriteString(fmt.Sprintf("// OrderBy%sDesc orders results by %s descending\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) OrderBy%sDesc() *%sQueryBuilder {\n", modelName, goFieldName, modelName))
			sb.WriteString("\tif q.orderBy == nil {\n")
			sb.WriteString("\t\tq.orderBy = builder.NewOrderByBuilder()\n")
			sb.WriteString("\t}\n")
			sb.WriteString(fmt.Sprintf("\tq.orderBy.Desc(\"%s\")\n", dbColumnName))
			sb.WriteString("\treturn q\n")
			sb.WriteString("}\n\n")
		}

		// Join methods
		sb.WriteString("// Join starts building JOIN clauses\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Join() *%sJoinBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.joins == nil {\n")
		sb.WriteString("\t\tq.joins = builder.NewJoinBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\treturn &%sJoinBuilder{\n", modelName))
		sb.WriteString("\t\tJoinBuilder: q.joins,\n")
		sb.WriteString("\t\tqueryBuilder: q,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// JoinBuilder type
		sb.WriteString(fmt.Sprintf("// %sJoinBuilder builds JOIN clauses for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sJoinBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.JoinBuilder\n")
		sb.WriteString("\tqueryBuilder *" + modelName + "QueryBuilder\n")
		sb.WriteString("}\n\n")

		// Done method for JoinBuilder
		sb.WriteString("// Done returns to the query builder\n")
		sb.WriteString(fmt.Sprintf("func (j *%sJoinBuilder) Done() *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\treturn j.queryBuilder\n")
		sb.WriteString("}\n\n")

		// Generate type-safe JOIN helper methods for relations
		for _, rel := range model.Relations {
			if rel.ForeignKey != "" {
				relatedModel := rel.RelatedModel
				relatedTableName := rel.ForeignKeyTable

				// Find the local key field name
				var localKeyFieldName string
				for _, field := range model.Fields {
					if toSnakeCase(field.Name) == toSnakeCase(rel.LocalKey) {
						localKeyFieldName = field.GoName
						break
					}
				}
				if localKeyFieldName == "" {
					localKeyFieldName = "ID" // Default to ID
				}

				// Find the foreign key field name in the related model
				// For now, we'll use a pattern - this could be improved
				fkFieldName := toPascalCase(rel.ForeignKey)

				// InnerJoin method
				sb.WriteString(fmt.Sprintf("// InnerJoin%s adds an INNER JOIN to %s\n", relatedModel, relatedModel))
				sb.WriteString(fmt.Sprintf("func (j *%sJoinBuilder) InnerJoin%s() *%sJoinBuilder {\n", modelName, relatedModel, modelName))
				sb.WriteString(fmt.Sprintf("\tcondition := builder.JoinConditionEQ(%s.%s, %s.%s)\n", modelName, localKeyFieldName, relatedModel, fkFieldName))
				sb.WriteString(fmt.Sprintf("\tj.InnerJoin(\"%s\", condition)\n", relatedTableName))
				sb.WriteString("\treturn j\n")
				sb.WriteString("}\n\n")

				// LeftJoin method
				sb.WriteString(fmt.Sprintf("// LeftJoin%s adds a LEFT JOIN to %s\n", relatedModel, relatedModel))
				sb.WriteString(fmt.Sprintf("func (j *%sJoinBuilder) LeftJoin%s() *%sJoinBuilder {\n", modelName, relatedModel, modelName))
				sb.WriteString(fmt.Sprintf("\tcondition := builder.JoinConditionEQ(%s.%s, %s.%s)\n", modelName, localKeyFieldName, relatedModel, fkFieldName))
				sb.WriteString(fmt.Sprintf("\tj.LeftJoin(\"%s\", condition)\n", relatedTableName))
				sb.WriteString("\treturn j\n")
				sb.WriteString("}\n\n")
			}
		}

		// Include method
		sb.WriteString("// Include starts building an INCLUDE clause for relations\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Include() *%sIncludeBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.include == nil {\n")
		sb.WriteString("\t\tq.include = builder.NewIncludeBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\treturn &%sIncludeBuilder{\n", modelName))
		sb.WriteString("\t\tIncludeBuilder: q.include,\n")
		sb.WriteString("\t\tqueryBuilder: q,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// IncludeBuilder type
		sb.WriteString(fmt.Sprintf("// %sIncludeBuilder builds INCLUDE clauses for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sIncludeBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.IncludeBuilder\n")
		sb.WriteString("\tqueryBuilder *" + modelName + "QueryBuilder\n")
		sb.WriteString("}\n\n")

		// Generate include methods for each relation field
		for _, field := range model.Fields {
			if field.IsRelation {
				fieldName := field.Name
				goFieldName := field.GoName
				relatedModel := field.RelationTo

				sb.WriteString(fmt.Sprintf("// %s includes the %s relation\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (i *%sIncludeBuilder) %s() *%sIncludeBuilder {\n", modelName, goFieldName, relatedModel))
				sb.WriteString(fmt.Sprintf("\ti.Include(\"%s\")\n", fieldName))
				// Return a builder for the related model to enable nested includes
				sb.WriteString(fmt.Sprintf("\treturn &%sIncludeBuilder{\n", relatedModel))
				sb.WriteString("\t\tIncludeBuilder: i.IncludeBuilder,\n")
				sb.WriteString("\t\tqueryBuilder: i.queryBuilder,\n")
				sb.WriteString("\t}\n")
				sb.WriteString("}\n\n")
			}
		}

		// Add Done() method to return to query builder
		sb.WriteString("// Done returns to the query builder\n")
		sb.WriteString(fmt.Sprintf("func (i *%sIncludeBuilder) Done() *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\treturn i.queryBuilder\n")
		sb.WriteString("}\n\n")

		// Select method
		sb.WriteString("// Select starts building a SELECT clause for fields\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Select() *%sSelectBuilder {\n", modelName, modelName))
		sb.WriteString("\tif q.select_ == nil {\n")
		sb.WriteString("\t\tq.select_ = builder.NewSelectBuilder()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\treturn &%sSelectBuilder{\n", modelName))
		sb.WriteString("\t\tSelectBuilder: q.select_,\n")
		sb.WriteString("\t\tqueryBuilder: q,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// SelectBuilder type
		sb.WriteString(fmt.Sprintf("// %sSelectBuilder builds SELECT clauses for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sSelectBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.SelectBuilder\n")
		sb.WriteString("\tqueryBuilder *" + modelName + "QueryBuilder\n")
		sb.WriteString("}\n\n")

		// Generate select methods for each non-relation field
		for _, field := range model.Fields {
			if !field.IsRelation {
				fieldName := field.Name
				goFieldName := field.GoName

				sb.WriteString(fmt.Sprintf("// %s selects the %s field\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (s *%sSelectBuilder) %s() *%sSelectBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString(fmt.Sprintf("\ts.Field(\"%s\")\n", fieldName))
				sb.WriteString("\treturn s\n")
				sb.WriteString("}\n\n")
			}
		}

		// Limit and Offset
		sb.WriteString("// Limit limits the number of results\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Limit(limit int) *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\tq.limit = &limit\n")
		sb.WriteString("\treturn q\n")
		sb.WriteString("}\n\n")

		sb.WriteString("// Offset skips the first N results\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Offset(offset int) *%sQueryBuilder {\n", modelName, modelName))
		sb.WriteString("\tq.offset = &offset\n")
		sb.WriteString("\treturn q\n")
		sb.WriteString("}\n\n")

		// Execute methods for QueryBuilder
		sb.WriteString("// Execute executes the query and returns all results\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) Execute(ctx context.Context) ([]%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tvar results []%s\n", modelName))
		sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
		sb.WriteString("\tif q.where != nil {\n")
		sb.WriteString("\t\twhereClause = q.where.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar orderBy []sqlgen.OrderBy\n")
		sb.WriteString("\tif q.orderBy != nil {\n")
		sb.WriteString("\t\torderBy = q.orderBy.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar include map[string]bool\n")
		sb.WriteString("\tif q.include != nil {\n")
		sb.WriteString("\t\tinclude = q.include.GetIncludes()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar selectFields map[string]bool\n")
		sb.WriteString("\tif q.select_ != nil {\n")
		sb.WriteString("\t\tselectFields = q.select_.GetFields()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\tif err := q.client.executor.FindManyWithRelations(ctx, q.client.table, selectFields, whereClause, orderBy, q.limit, q.offset, include, q.client.relations, &results); err != nil {\n"))
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn results, nil\n")
		sb.WriteString("}\n\n")

		sb.WriteString("// ExecuteFirst executes the query and returns the first result\n")
		sb.WriteString(fmt.Sprintf("func (q *%sQueryBuilder) ExecuteFirst(ctx context.Context) (*%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tvar result %s\n", modelName))
		sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
		sb.WriteString("\tif q.where != nil {\n")
		sb.WriteString("\t\twhereClause = q.where.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar joins []sqlgen.Join\n")
		sb.WriteString("\tif q.joins != nil {\n")
		sb.WriteString("\t\tjoins = q.joins.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar orderBy []sqlgen.OrderBy\n")
		sb.WriteString("\tif q.orderBy != nil {\n")
		sb.WriteString("\t\torderBy = q.orderBy.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar include map[string]bool\n")
		sb.WriteString("\tif q.include != nil {\n")
		sb.WriteString("\t\tinclude = q.include.GetIncludes()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tvar selectFields map[string]bool\n")
		sb.WriteString("\tif q.select_ != nil {\n")
		sb.WriteString("\t\tselectFields = q.select_.GetFields()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\tif err := q.client.executor.FindFirstWithJoins(ctx, q.client.table, selectFields, joins, whereClause, orderBy, include, q.client.relations, &result); err != nil {\n"))
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn &result, nil\n")
		sb.WriteString("}\n\n")

		// Generate field-specific filter methods
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)
			goType := field.GoType

			// Equals
			sb.WriteString(fmt.Sprintf("// %sEquals filters where %s equals the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sEquals(value %s) *%sWhereBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\tw.Equals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn w\n")
			sb.WriteString("}\n\n")

			// NotEquals
			sb.WriteString(fmt.Sprintf("// %sNotEquals filters where %s does not equal the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sNotEquals(value %s) *%sWhereBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\tw.NotEquals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn w\n")
			sb.WriteString("}\n\n")

			// For numeric types
			if isNumericType(goType) {
				sb.WriteString(fmt.Sprintf("// %sGreaterThan filters where %s is greater than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sGreaterThan(value %s) *%sWhereBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\tw.GreaterThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sLessThan filters where %s is less than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sLessThan(value %s) *%sWhereBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\tw.LessThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")
			}

			// For string types
			if goType == "string" || strings.HasPrefix(goType, "*string") {
				sb.WriteString(fmt.Sprintf("// %sContains filters where %s contains the substring\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sContains(value string) *%sWhereBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString(fmt.Sprintf("\tw.Like(\"%s\", \"%%\"+value+\"%%\")\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")
			}

			// For optional fields
			if strings.HasPrefix(goType, "*") {
				sb.WriteString(fmt.Sprintf("// %sIsNull filters where %s is NULL\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sIsNull() *%sWhereBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString(fmt.Sprintf("\tw.IsNull(\"%s\")\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sIsNotNull filters where %s is not NULL\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sWhereBuilder) %sIsNotNull() *%sWhereBuilder {\n", modelName, goFieldName, modelName))
				sb.WriteString(fmt.Sprintf("\tw.IsNotNull(\"%s\")\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")
			}
		}

		// Create
		sb.WriteString(fmt.Sprintf("// Create creates a new %s record\n", modelName))
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Create(ctx context.Context, data %s) (*%s, error) {\n", modelName, modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tresult, err := c.executor.Create(ctx, c.table, data)\n"))
		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\tif created, ok := result.(*%s); ok {\n", modelName))
		sb.WriteString("\t\treturn created, nil\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn &data, nil\n")
		sb.WriteString("}\n\n")

		// UpdateBuilder type
		sb.WriteString(fmt.Sprintf("// %sUpdateBuilder builds UPDATE queries for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sUpdateBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.UpdateBuilder\n")
		sb.WriteString("\tclient *" + modelName + "Client\n")
		sb.WriteString("}\n\n")

		// Update method
		sb.WriteString("// Update starts building an UPDATE query\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Update() *%sUpdateBuilder {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn &%sUpdateBuilder{\n", modelName))
		sb.WriteString("\t\tUpdateBuilder: builder.NewUpdateBuilder(),\n")
		sb.WriteString("\t\tclient: c,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// UpdateWhereBuilder - special WhereBuilder for Update operations
		sb.WriteString(fmt.Sprintf("// %sUpdateWhereBuilder is a WhereBuilder for Update operations\n", modelName))
		sb.WriteString(fmt.Sprintf("type %sUpdateWhereBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.WhereBuilder\n")
		sb.WriteString("\tupdateBuilder *" + modelName + "UpdateBuilder\n")
		sb.WriteString("}\n\n")

		// Execute method for UpdateWhereBuilder
		sb.WriteString("// Execute executes the UPDATE query\n")
		sb.WriteString(fmt.Sprintf("func (w *%sUpdateWhereBuilder) Execute(ctx context.Context) (*%s, error) {\n", modelName, modelName))
		sb.WriteString("\treturn w.updateBuilder.Execute(ctx)\n")
		sb.WriteString("}\n\n")

		// Where method for UpdateBuilder
		sb.WriteString("// Where adds a WHERE clause to the UPDATE query\n")
		sb.WriteString(fmt.Sprintf("func (u *%sUpdateBuilder) Where() *%sUpdateWhereBuilder {\n", modelName, modelName))
		sb.WriteString("\tif u.UpdateBuilder.GetWhere() == nil {\n")
		sb.WriteString("\t\tu.UpdateBuilder.Where()\n")
		sb.WriteString("\t}\n")
		sb.WriteString(fmt.Sprintf("\treturn &%sUpdateWhereBuilder{\n", modelName))
		sb.WriteString("\t\tWhereBuilder: u.UpdateBuilder.Where(),\n")
		sb.WriteString("\t\tupdateBuilder: u,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// Generate field-specific filter methods for UpdateWhereBuilder
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)
			goType := field.GoType

			// Equals
			sb.WriteString(fmt.Sprintf("// %sEquals filters where %s equals the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (w *%sUpdateWhereBuilder) %sEquals(value %s) *%sUpdateWhereBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\tw.Equals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn w\n")
			sb.WriteString("}\n\n")

			// NotEquals
			sb.WriteString(fmt.Sprintf("// %sNotEquals filters where %s does not equal the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (w *%sUpdateWhereBuilder) %sNotEquals(value %s) *%sUpdateWhereBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\tw.NotEquals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn w\n")
			sb.WriteString("}\n\n")

			// For numeric types
			if isNumericType(goType) {
				sb.WriteString(fmt.Sprintf("// %sGreaterThan filters where %s is greater than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sUpdateWhereBuilder) %sGreaterThan(value %s) *%sUpdateWhereBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\tw.GreaterThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sLessThan filters where %s is less than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (w *%sUpdateWhereBuilder) %sLessThan(value %s) *%sUpdateWhereBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\tw.LessThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn w\n")
				sb.WriteString("}\n\n")
			}
		}

		// Generate field-specific set methods
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)
			goType := field.GoType

			// Set method
			sb.WriteString(fmt.Sprintf("// Set%s sets the %s field\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (u *%sUpdateBuilder) Set%s(value %s) *%sUpdateBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\tu.Set(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn u\n")
			sb.WriteString("}\n\n")
		}

		// Execute method for UpdateBuilder
		sb.WriteString("// Execute executes the UPDATE query\n")
		sb.WriteString(fmt.Sprintf("func (u *%sUpdateBuilder) Execute(ctx context.Context) (*%s, error) {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\tvar result %s\n", modelName))
		sb.WriteString("\twhereClause := u.GetWhere()\n")
		sb.WriteString(fmt.Sprintf("\tif err := u.client.executor.Update(ctx, u.client.table, u.GetSet(), whereClause, &result); err != nil {\n"))
		sb.WriteString("\t\treturn nil, err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn &result, nil\n")
		sb.WriteString("}\n\n")

		// DeleteBuilder type
		sb.WriteString(fmt.Sprintf("// %sDeleteBuilder builds DELETE queries for %s\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("type %sDeleteBuilder struct {\n", modelName))
		sb.WriteString("\t*builder.WhereBuilder\n")
		sb.WriteString("\tclient *" + modelName + "Client\n")
		sb.WriteString("}\n\n")

		// Delete method
		sb.WriteString("// Delete starts building a DELETE query\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Delete() *%sDeleteBuilder {\n", modelName, modelName))
		sb.WriteString(fmt.Sprintf("\treturn &%sDeleteBuilder{\n", modelName))
		sb.WriteString("\t\tWhereBuilder: builder.NewWhereBuilder(),\n")
		sb.WriteString("\t\tclient: c,\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// Generate field-specific filter methods for DeleteBuilder
		for _, field := range model.Fields {
			fieldName := field.Name
			goFieldName := field.GoName
			dbColumnName := toSnakeCase(fieldName)
			goType := field.GoType

			// Equals
			sb.WriteString(fmt.Sprintf("// %sEquals filters where %s equals the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (d *%sDeleteBuilder) %sEquals(value %s) *%sDeleteBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\td.Equals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn d\n")
			sb.WriteString("}\n\n")

			// NotEquals
			sb.WriteString(fmt.Sprintf("// %sNotEquals filters where %s does not equal the value\n", goFieldName, fieldName))
			sb.WriteString(fmt.Sprintf("func (d *%sDeleteBuilder) %sNotEquals(value %s) *%sDeleteBuilder {\n", modelName, goFieldName, goType, modelName))
			sb.WriteString(fmt.Sprintf("\td.NotEquals(\"%s\", value)\n", dbColumnName))
			sb.WriteString("\treturn d\n")
			sb.WriteString("}\n\n")

			// For numeric types
			if isNumericType(goType) {
				sb.WriteString(fmt.Sprintf("// %sGreaterThan filters where %s is greater than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (d *%sDeleteBuilder) %sGreaterThan(value %s) *%sDeleteBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\td.GreaterThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn d\n")
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// %sLessThan filters where %s is less than the value\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (d *%sDeleteBuilder) %sLessThan(value %s) *%sDeleteBuilder {\n", modelName, goFieldName, goType, modelName))
				sb.WriteString(fmt.Sprintf("\td.LessThan(\"%s\", value)\n", dbColumnName))
				sb.WriteString("\treturn d\n")
				sb.WriteString("}\n\n")
			}
		}

		// Execute method for DeleteBuilder
		sb.WriteString("// Execute executes the DELETE query\n")
		sb.WriteString(fmt.Sprintf("func (d *%sDeleteBuilder) Execute(ctx context.Context) error {\n", modelName))
		sb.WriteString("\twhereClause := d.Build()\n")
		sb.WriteString(fmt.Sprintf("\treturn d.client.executor.Delete(ctx, d.client.table, whereClause)\n"))
		sb.WriteString("}\n\n")

		// Aggregation methods
		sb.WriteString("// Count counts the number of records\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) Count(ctx context.Context) (int64, error) {\n", modelName))
		sb.WriteString("\treturn c.executor.Count(ctx, c.table, nil)\n")
		sb.WriteString("}\n\n")

		sb.WriteString("// CountWhere counts records matching the WHERE clause\n")
		sb.WriteString(fmt.Sprintf("func (c *%sClient) CountWhere(ctx context.Context, where *builder.WhereBuilder) (int64, error) {\n", modelName))
		sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
		sb.WriteString("\tif where != nil {\n")
		sb.WriteString("\t\twhereClause = where.Build()\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn c.executor.Count(ctx, c.table, whereClause)\n")
		sb.WriteString("}\n\n")

		// Generate Sum/Avg/Min/Max for numeric fields
		for _, field := range model.Fields {
			if !field.IsRelation && isNumericType(field.GoType) {
				fieldName := field.Name
				goFieldName := field.GoName
				dbColumnName := toSnakeCase(fieldName)

				// Sum
				sb.WriteString(fmt.Sprintf("// Sum%s calculates the sum of %s\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Sum%s(ctx context.Context) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Sum(ctx, c.table, \"%s\", nil)\n", dbColumnName))
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// Sum%sWhere calculates the sum of %s with WHERE clause\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Sum%sWhere(ctx context.Context, where *builder.WhereBuilder) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
				sb.WriteString("\tif where != nil {\n")
				sb.WriteString("\t\twhereClause = where.Build()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Sum(ctx, c.table, \"%s\", whereClause)\n", dbColumnName))
				sb.WriteString("}\n\n")

				// Avg
				sb.WriteString(fmt.Sprintf("// Avg%s calculates the average of %s\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Avg%s(ctx context.Context) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Avg(ctx, c.table, \"%s\", nil)\n", dbColumnName))
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// Avg%sWhere calculates the average of %s with WHERE clause\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Avg%sWhere(ctx context.Context, where *builder.WhereBuilder) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
				sb.WriteString("\tif where != nil {\n")
				sb.WriteString("\t\twhereClause = where.Build()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Avg(ctx, c.table, \"%s\", whereClause)\n", dbColumnName))
				sb.WriteString("}\n\n")

				// Min
				sb.WriteString(fmt.Sprintf("// Min%s finds the minimum value of %s\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Min%s(ctx context.Context) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Min(ctx, c.table, \"%s\", nil)\n", dbColumnName))
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// Min%sWhere finds the minimum value of %s with WHERE clause\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Min%sWhere(ctx context.Context, where *builder.WhereBuilder) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
				sb.WriteString("\tif where != nil {\n")
				sb.WriteString("\t\twhereClause = where.Build()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Min(ctx, c.table, \"%s\", whereClause)\n", dbColumnName))
				sb.WriteString("}\n\n")

				// Max
				sb.WriteString(fmt.Sprintf("// Max%s finds the maximum value of %s\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Max%s(ctx context.Context) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Max(ctx, c.table, \"%s\", nil)\n", dbColumnName))
				sb.WriteString("}\n\n")

				sb.WriteString(fmt.Sprintf("// Max%sWhere finds the maximum value of %s with WHERE clause\n", goFieldName, fieldName))
				sb.WriteString(fmt.Sprintf("func (c *%sClient) Max%sWhere(ctx context.Context, where *builder.WhereBuilder) (float64, error) {\n", modelName, goFieldName))
				sb.WriteString("\tvar whereClause *sqlgen.WhereClause\n")
				sb.WriteString("\tif where != nil {\n")
				sb.WriteString("\t\twhereClause = where.Build()\n")
				sb.WriteString("\t}\n")
				sb.WriteString(fmt.Sprintf("\treturn c.executor.Max(ctx, c.table, \"%s\", whereClause)\n", dbColumnName))
				sb.WriteString("}\n\n")
			}
		}
	}

	// Write to file
	filePath := filepath.Join(outputDir, "client.go")
	if err := os.WriteFile(filePath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write client file: %w", err)
	}

	return nil
}
