// Package writer implements the code writing pipeline.
package writer

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"

	"github.com/satishbabariya/prisma-go/v3/internal/core/generator/ir"
	"github.com/satishbabariya/prisma-go/v3/internal/core/generator/template"
)

// Writer writes AST nodes to Go code.
type Writer interface {
	Write(w io.Writer, node ast.Node) error
}

// Pipeline executes multiple writers in sequence.
type Pipeline struct {
	stages         []Writer
	templateEngine *template.Engine
}

// NewPipeline creates a new pipeline.
func NewPipeline(templateEngine *template.Engine, stages ...Writer) *Pipeline {
	return &Pipeline{
		stages:         stages,
		templateEngine: templateEngine,
	}
}

// Execute executes the pipeline.
func (p *Pipeline) Execute(ir *ir.IR) ([]byte, error) {
	var buf bytes.Buffer

	// If template engine is available, use it to render all templates
	if p.templateEngine != nil {
		files, err := p.templateEngine.RenderAll(ir)
		if err != nil {
			return nil, fmt.Errorf("template rendering failed: %w", err)
		}

		// Combine all files into one output for now
		for filename, content := range files {
			buf.WriteString("// --- " + filename + " ---\n")
			buf.Write(content)
			buf.WriteString("\n\n")
		}
		return buf.Bytes(), nil
	}

	// Fallback to empty result
	return buf.Bytes(), nil
}

// ASTWriter writes AST nodes to formatted Go code.
type ASTWriter struct {
	fset *token.FileSet
}

// NewASTWriter creates a new AST writer.
func NewASTWriter() *ASTWriter {
	return &ASTWriter{
		fset: token.NewFileSet(),
	}
}

// Write writes an AST node to the writer.
func (w *ASTWriter) Write(writer io.Writer, node ast.Node) error {
	// Format the AST
	var buf bytes.Buffer
	if err := format.Node(&buf, w.fset, node); err != nil {
		return fmt.Errorf("failed to format AST: %w", err)
	}

	// Write to output
	if _, err := writer.Write(buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write output: %w", err)
	}

	return nil
}

// ModelWriter writes model structs.
type ModelWriter struct {
	astWriter *ASTWriter
}

// NewModelWriter creates a new model writer.
func NewModelWriter() *ModelWriter {
	return &ModelWriter{
		astWriter: NewASTWriter(),
	}
}

// Write writes models to the writer.
func (w *ModelWriter) Write(writer io.Writer, node ast.Node) error {
	return w.astWriter.Write(writer, node)
}

// FileHeader writes a file header comment.
type FileHeader struct{}

// NewFileHeader creates a new file header writer.
func NewFileHeader() *FileHeader {
	return &FileHeader{}
}

// Write writes the file header.
func (h *FileHeader) Write(w io.Writer, node ast.Node) error {
	header := "// Code generated by prisma-go. DO NOT EDIT.\n\n"
	_, err := w.Write([]byte(header))
	return err
}
